Update push logic

diff --git a/.github/workflows/build_marketplace.yaml b/.github/workflows/build_marketplace.yaml
--- a/.github/workflows/build_marketplace.yaml
+++ b/.github/workflows/build_marketplace.yaml
@@ -16,9 +16,6 @@ jobs:
       - name: Get branch name
         id: branch
         run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
-      - name: Get current date
-        id: date
-        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"
       - name: Checkout current repo
         uses: actions/checkout@v2
         with:
@@ -45,9 +42,28 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.MARKETPLACE_ACCESS_TOKEN }}
         run: |
           cd marketplace
-          git config user.name "github-ci"
-          branch='marketplace-doc-gen-${{ steps.branch.outputs.branch }}-${{ steps.date.outputs.date }}'
-          echo $branch
-          git checkout -b $branch
-          git add -A && git commit -m "Automated build"
-          git push --set-upstream origin $branch
+
+          COMMIT_SHA=$(git rev-parse --short "$GITHUB_SHA")
+          BRANCH_NAME=marketplace-doc-gen-$COMMIT_SHA
+          REMOTE=***github.com/$USERNAME/$REPO_PATH.git
+
+          echo "Validating environment params...";
+
+          [ -z "${GITHUB_TOKEN}" ] && {
+              echo 'Missing input "GITHUB_TOKEN: ***".';
+              exit 1;
+          };
+
+          git config --local user.name "github-worflow[bot]"
+
+          echo "Checking out [$BRANCH_NAME]..."
+          git checkout -b $BRANCH_NAME
+
+          echo "Commiting changes..."
+          git add -A && git commit -m "Automatically generated by github-worflow[bot] for commit: $COMMIT_SHA"
+
+          echo "Pushing [$BRANCH_NAME] to remote [$REMOTE]"
+          git push $REMOTE $BRANCH_NAME
+
+          echo "Submiting pull request..."
+          gh pr create --title "Marketplace update from $BRANCH_NAME" --body "github-workflow" --base $BASE_BRANCH --head $BRANCH_NAME --repo $USERNAME/$REPO_PATH
