test matrix echo

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -12,115 +12,127 @@ on:
       - master
 
 jobs:
-  tests:
-    name: Run tests
-    runs-on: self-hosted
-    steps:
-      # Source
-      - name: Checkout current repo
-        uses: actions/checkout@v2
-        with:
-          path: functions
-      # Install python
-      - name: Install python
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.7
-      # Install dependencies
-      - uses: actions/cache@v1
-        id: cache
-        with:
-          path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('functions/requirements.txt') }}
-          restore-keys: |
-            ${{ runner.os }}-pip-
-      - name: Install requirements
-        run: |
-          pip install --upgrade pip
-          pip install -r functions/requirements.txt
-      - name: Run item validation
-        run: python functions/functions.py  run-tests -r functions -s items
-      - name: Run py tests
-        run: python functions/functions.py  run-tests -r functions -s py -mp True
-#      - name: Run ipynb tests
-#        run: python functions/functions.py  run-tests -r functions -s ipynb
-      - name: Clean
-        run: |
-          rm -rf functions
-
-  build-marketplace:
-    name: Build marketplace
-    if: github.repository == 'mlrun/functions' && github.event_name != 'pull_request'
+  get_last_changes:
     runs-on: ubuntu-latest
-    needs: tests
 
     steps:
-      - name: Get branch name
-        id: branch
-        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
-      - name: Checkout current repo
-        uses: actions/checkout@v2
-        with:
-          path: functions
-      - name: Checkout Marketplace
-        uses: actions/checkout@v2
-        with:
-          repository: mlrun/marketplace
-          path: marketplace
-      - name: Install python
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.7
-      - name: Install requirements
-        run: |
-          cd functions
-          pip install --upgrade pip
-          pip install -r requirements.txt
-      - name: Build marketplace docs
-        env:
-          CHANNEL: ${{ steps.branch.outputs.branch }}
-        run: |
-          cd marketplace
-          git pull origin
-          cd ..
-          python functions/functions.py build-marketplace -s functions -sn functions -m marketplace -c $CHANNEL -v
-      - name: Publish marketplace release
-        env:
-          GITHUB_TOKEN: ${{ secrets.MARKETPLACE_ACCESS_TOKEN_V2 }}
-          USERNAME: Michaelliv
-          REPO_PATH: marketplace
-          BASE_REPO: mlrun
-          BASE_BRANCH: master
-        run: |
-          cd marketplace
+      - uses: actions/checkout@v2
+      - id: set-matrix
+        run: echo "::set-output name=matrix::$(git diff --dirstat=files,0 HEAD~1 | sed 's/^[ 0-9.]\+% //g')"
 
-          COMMIT_SHA=$(git rev-parse --short "$GITHUB_SHA")
-          BRANCH_NAME=marketplace-doc-gen-$COMMIT_SHA
-          REMOTE=https://$USERNAME:$GITHUB_TOKEN@github.com/$BASE_REPO/$REPO_PATH.git
+    # here, we save the result of this 1st phase to the "outputs"
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
 
-          echo "Validating environment params...";
+#    tests:
+#    name: Run tests
+#    runs-on: self-hosted
+#    steps:
+#      # Source
+#      - name: Checkout current repo
+#        uses: actions/checkout@v2
+#        with:
+#          path: functions
+#      # Install python
+#      - name: Install python
+#        uses: actions/setup-python@v2
+#        with:
+#          python-version: 3.7
+#      # Install dependencies
+#      - uses: actions/cache@v1
+#        id: cache
+#        with:
+#          path: ~/.cache/pip
+#          key: ${{ runner.os }}-pip-${{ hashFiles('functions/requirements.txt') }}
+#          restore-keys: |
+#            ${{ runner.os }}-pip-
+#      - name: Install requirements
+#        run: |
+#          pip install --upgrade pip
+#          pip install -r functions/requirements.txt
+#      - name: Run item validation
+#        run: python functions/functions.py  run-tests -r functions -s items
+#      - name: Run py tests
+#        run: python functions/functions.py  run-tests -r functions -s py -mp True
+##      - name: Run ipynb tests
+##        run: python functions/functions.py  run-tests -r functions -s ipynb
+#      - name: Clean
+#        run: |
+#          rm -rf functions
 
-          [ -z "${GITHUB_TOKEN}" ] && {
-              echo 'Missing input "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}".';
-              exit 1;
-          };
-
-          git config --local user.name $USERNAME
-
-          echo "Checking out [$BRANCH_NAME]..."
-          git checkout -b $BRANCH_NAME
-
-          git merge --ff-only origin/master
-
-          echo "Commiting changes..."
-          git add -A && git commit -m "Automatically generated by github-worflow[bot] for commit: $COMMIT_SHA"
-
-          # https://stackoverflow.com/questions/64270867/auth-error-trying-to-copy-a-repo-with-github-actions
-          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
-
-          echo "Pushing [$BRANCH_NAME] to remote [$REMOTE]"
-
-          git push $REMOTE $BRANCH_NAME
-
-          echo "Submiting pull request..."
-          gh pr create --title "Marketplace update from $BRANCH_NAME" --body "github-workflow" --base $BASE_BRANCH --head $BRANCH_NAME --repo $BASE_REPO/$REPO_PATH
+#  build-marketplace:
+#    name: Build marketplace
+#    if: github.repository == 'mlrun/functions' && github.event_name != 'pull_request'
+#    runs-on: ubuntu-latest
+#    needs: tests
+#
+#    steps:
+#      - name: Get branch name
+#        id: branch
+#        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
+#      - name: Checkout current repo
+#        uses: actions/checkout@v2
+#        with:
+#          path: functions
+#      - name: Checkout Marketplace
+#        uses: actions/checkout@v2
+#        with:
+#          repository: mlrun/marketplace
+#          path: marketplace
+#      - name: Install python
+#        uses: actions/setup-python@v2
+#        with:
+#          python-version: 3.7
+#      - name: Install requirements
+#        run: |
+#          cd functions
+#          pip install --upgrade pip
+#          pip install -r requirements.txt
+#      - name: Build marketplace docs
+#        env:
+#          CHANNEL: ${{ steps.branch.outputs.branch }}
+#        run: |
+#          cd marketplace
+#          git pull origin
+#          cd ..
+#          python functions/functions.py build-marketplace -s functions -sn functions -m marketplace -c $CHANNEL -v
+#      - name: Publish marketplace release
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.MARKETPLACE_ACCESS_TOKEN_V2 }}
+#          USERNAME: Michaelliv
+#          REPO_PATH: marketplace
+#          BASE_REPO: mlrun
+#          BASE_BRANCH: master
+#        run: |
+#          cd marketplace
+#
+#          COMMIT_SHA=$(git rev-parse --short "$GITHUB_SHA")
+#          BRANCH_NAME=marketplace-doc-gen-$COMMIT_SHA
+#          REMOTE=https://$USERNAME:$GITHUB_TOKEN@github.com/$BASE_REPO/$REPO_PATH.git
+#
+#          echo "Validating environment params...";
+#
+#          [ -z "${GITHUB_TOKEN}" ] && {
+#              echo 'Missing input "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}".';
+#              exit 1;
+#          };
+#
+#          git config --local user.name $USERNAME
+#
+#          echo "Checking out [$BRANCH_NAME]..."
+#          git checkout -b $BRANCH_NAME
+#
+#          git merge --ff-only origin/master
+#
+#          echo "Commiting changes..."
+#          git add -A && git commit -m "Automatically generated by github-worflow[bot] for commit: $COMMIT_SHA"
+#
+#          # https://stackoverflow.com/questions/64270867/auth-error-trying-to-copy-a-repo-with-github-actions
+#          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
+#
+#          echo "Pushing [$BRANCH_NAME] to remote [$REMOTE]"
+#
+#          git push $REMOTE $BRANCH_NAME
+#
+#          echo "Submiting pull request..."
+#          gh pr create --title "Marketplace update from $BRANCH_NAME" --body "github-workflow" --base $BASE_BRANCH --head $BRANCH_NAME --repo $BASE_REPO/$REPO_PATH
