final workflow

diff --git a/.github/workflows/test-all.yaml b/.github/workflows/test-all.yaml
--- a/.github/workflows/test-all.yaml
+++ b/.github/workflows/test-all.yaml
@@ -6,7 +6,6 @@ on:
     branches:
       - development
       - master
-      - add-stes-asset
   workflow_dispatch: {}
 
 jobs:
@@ -154,6 +153,7 @@ jobs:
 
   build-marketplace:
     name: Build marketplace
+    if: (github.repository == 'mlrun/functions' || github.repository == 'mlrun/hub-assets')
     runs-on: ubuntu-latest
     needs: run_monorepo_tests
     continue-on-error: false
@@ -189,8 +189,64 @@ jobs:
           python -m cli.cli build-marketplace -s ./functions/src -sn functions -m marketplace -c $CHANNEL -v -f
           python -m cli.cli build-marketplace -s ./modules/src -sn modules -m marketplace -c $CHANNEL -v -f
           python -m cli.cli build-marketplace -s ./steps/src -sn steps -m marketplace -c $CHANNEL -v -f
-      - name: Upload built marketplace as artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: marketplace-build
-          path: marketplace/**
+      ## Uncomment the following lines if you want to upload the built marketplace as an artifact
+#      - name: Upload built marketplace as artifact
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: marketplace-build
+#          path: marketplace/**
+      - name: Publish marketplace release
+        env:
+          GITHUB_TOKEN: ${{ secrets.MARKETPLACE_ACCESS_TOKEN_V3 }}
+          USERNAME: ${{ secrets.USERNAME }}
+          USEREMAIL: ${{ secrets.USERMAIL }}
+          REPO_PATH: marketplace
+          BASE_REPO: mlrun
+          BASE_BRANCH: master
+        run: |
+          cd marketplace
+          pwd
+          COMMIT_SHA=$(git rev-parse --short "$GITHUB_SHA")
+          echo "commit sha: $COMMIT_SHA"
+          echo "github sha: $GITHUB_SHA"
+          BRANCH_NAME=marketplace-doc-gen-$COMMIT_SHA
+          REMOTE=https://$USERNAME:$GITHUB_TOKEN@github.com/$BASE_REPO/$REPO_PATH.git
+          echo "Validating environment params...";
+          [ -z "${GITHUB_TOKEN}" ] && {
+              echo 'Missing input "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}".';
+              exit 1;
+          };
+          git config --local user.name $USERNAME
+          git config --local user.email $USEREMAIL
+          git branch --set-upstream-to origin/master
+          git remote -v
+          echo "1. Checking out [$BRANCH_NAME]..."
+          git checkout -b $BRANCH_NAME
+          echo "2. Checking out [$BASE_BRANCH]..."
+          git checkout $BASE_BRANCH
+          git pull
+          echo "3. Checking out [$BRANCH_NAME]..."
+          git checkout $BRANCH_NAME
+          echo "3a. merging"
+          git merge $BASE_BRANCH
+          echo "3b. status"
+          git status
+          git status --ignored
+          find . -type f | xargs ls -artl
+          echo "3b. add"
+          git add --all 
+          git status
+          git status --ignored
+          echo "4. Commiting changes..."
+          echo "4a. git rev-parse"
+          git rev-parse --show-toplevel
+          echo "4b. git commit"
+          git commit -a -m "Automatically generated by github-worflow[bot] for commit: $COMMIT_SHA"
+          git status
+          git status --ignored
+          # https://stackoverflow.com/questions/64270867/auth-error-trying-to-copy-a-repo-with-github-actions
+          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
+          echo "Pushing [$BRANCH_NAME] to remote [$REMOTE]"
+          git push -f $REMOTE $BRANCH_NAME
+          echo "Submiting pull request..."
+          gh pr create --title "Marketplace update from $BRANCH_NAME" --body "github-workflow" --base $BASE_BRANCH --head $BRANCH_NAME --repo $BASE_REPO/$REPO_PATH
